### ISSUE TITLE
Content-Type error from Stripe API

### ISSUE THREAD

**Issue by tarikstafford** [vapor-community/stripe-provider#39]
Hey guys,

Sorry to bother, another issue. I am getting an error response from the stripe API declaring a content-type error. Not sure what the issue is, will try and do some digging.
```
"Invalid request: unsupported Content-Type text/plain; charset=utf-8. If error persists and you need assistance, please contact support@stripe.com."
```

**Comment by Andrewangeta** [comment]
What was the issue?

**Comment by tarikstafford** [comment]
@Andrewangeta I still don't know. I am trying to solve it, but closed it till I do more digging.

**Comment by tarikstafford** [comment]
@Andrewangeta did a fresh vapor proj to test it and it's also not working so it must be an issue with the new StripeRequest being sent to the StripeAPI.

**Comment by tarikstafford** [comment]
@Andrewangeta 
```
try body.encode(request)
```
this at least doesn't get an error but the content does not go through.

```
try request.content.encode(body, as: .urlEncodedForm)
```

**Comment by Andrewangeta** [comment]
@tarikstafford I know the issue. Pushing a fix now.

**Comment by Andrewangeta** [comment]
@tarikstafford `2.0.7` tag should fix the issue.

**Comment by anagpal1990** [comment]
Hi Team, did we get any fix to this issue, i'm still getting same error in response from API call from Stripe.

**Comment by anthonycastelli** [comment]
@anuj-inecta What version of the provider are you running? This should of been resolved long ago.

**Comment by anagpal1990** [comment]
Hi @anthonycastelli , thanks for revert..
Actually, we got this issue while running the App Monetization code which integrates Dynamics 365 Business Central with Stripe. Same code was working fine earlier but suddenly it started giving this error.
Lucking, after some digging yesterday, i found one bug in the code for web request call and fixed the issue.

**Comment by mohsinJanjua** [comment]
> Hi @anthonycastelli , thanks for revert..
> Actually, we got this issue while running the App Monetization code which integrates Dynamics 365 Business Central with Stripe. Same code was working fine earlier but suddenly it started giving this error.
> Lucking, after some digging yesterday, i found one bug in the code for web request call and fixed the issue.

Hi @anuj-inecta 
I'm facing exactly same issue. the code for app monetization was working fine. then we upgraded to the October release of Business Central and it is now giving me this issue. Can you please tell me what exactly was the probelm? It will be a great help.
Thank you in advance.

**Comment by anagpal1990** [comment]
Hi @mohsinJanjua , there was a small bug in the code that i found. 
If you see in Cod50298.StripeWebService.al, there is one line of code `Arguments.SetRequestContent(RequestContent)`. Here it was called before setting Header "Content Type". So later, when `If not CallWebService(Arguments) then` is called, it didn't had the `Content-Type` set. 
I also checked for API logs on stripe portal and it was sending blank JSON as request and was getting same error as mentioned above.
To fix this issue, i called `Arguments.SetRequestContent(RequestContent)` after adding request header. 
Not sure, how it was working fine earlier but this fixed the issue for me.

> Note - Above fix is required to be applied in all functions i.e CreateCustomer, UpdateCustomer, CreateSubscription etc.

![image](https://user-images.githubusercontent.com/40057282/48533262-b48cd880-e8c9-11e8-98a0-efb56f0bd037.png)

**Comment by mohsinJanjua** [comment]
> Hi @mohsinJanjua , there was a small bug in the code that i found.
> If you see in Cod50298.StripeWebService.al, there is one line of code `Arguments.SetRequestContent(RequestContent)`. Here it was called before setting Header "Content Type". So later, when `If not CallWebService(Arguments) then` is called, it didn't had the `Content-Type` set.
> I also checked for API logs on stripe portal and it was sending blank JSON as request and was getting same error as mentioned above.
> To fix this issue, i called `Arguments.SetRequestContent(RequestContent)` after adding request header.
> Not sure, how it was working fine earlier but this fixed the issue for me.
> 
> > Note - Above fix is required to be applied in all functions i.e CreateCustomer, UpdateCustomer, CreateSubscription etc.
> 
> ![image](https://user-images.githubusercontent.com/40057282/48533262-b48cd880-e8c9-11e8-98a0-efb56f0bd037.png)

Thanks a lot, @anuj-inecta  :)
